### ISSUE TITLE
曲のBPM表記について

### ISSUE THREAD

**Issue by sakusancarmin** [koiking213/step-viewer#18]
今の仕様は恐らく譜面データの最大bpmを表示していると思うが、
そうすると例えば演出のための急加速をするような譜面のBPM表記がおかしくなる。
（例：けもののおうじゃ）

譜面データにDISPLAYBPMが設定されているものについては、そちらを表示するようにしたほうが
いいような気がします。

**Comment by koiking213** [comment]
反映したので確認してみてください
ついでに整数表記、`min-max`、ソート順はmax準拠にしました

**Comment by sakusancarmin** [comment]
ありがとうございます。OKとおもいます
